name: "MooGooMaps"
exports: "mootools-moogoomaps.js"
web: "[mooforum.net](http://mooforum.net)"
description: "MooTools Google Maps"
license: "[MIT License](http://mootools.net/license.txt)"
copyright: "&copy; [mooforum](http://mooforum.net)"
authors: "[Thomas Allmer](http://mooforum.net)"

author: Ciul
category: Interface
tags: [map, googlemaps, googlemap, google]
#docs: http://url.to.docs
#demo: http://url.to.demo
#current: 0.5

sources:
  - "Source/Class.SubObjectMapping.js"
  - "Source/Class.XML2Js.js"
  - "Source/Map.js"
  - "Source/Map.Circle.js"
  - "Source/Map.Extras.js"
  - "Source/Map.FullScreenMarker.js"
  - "Source/Map.Geocoder.js"
  - "Source/Map.GroundOverlay.js"
  - "Source/Map.InfoMarker.js"
  - "Source/Map.InfoWindow.js"
  - "Source/Map.Marker.js"
  - "Source/Map.Opt_InfoMarker.js"
  - "Source/Map.OverlayView.js"
  - "Source/Map.Polygon.js"
  - "Source/Map.PolyLine.Advanced.js"
  - "Source/Map.PolyLine.Animated.js"
  - "Source/Map.Polyline.js"
  - "Source/Map.Rectangle.js"
  - "Source/Map.XMLMap.js"
  - "Source/Plugins/Map.Plugin.Bounds.js"
  - "Source/Plugins/Map.Plugin.MarkerFilter.js"
  - "Source/Plugins/Map.Plugin.Play.js"
  - "Source/Plugins/Map.Plugin.Seeker.js"
  - "Source/Behaviors/Behavior.Map.js"
  - "Source/Behaviors/Behavior.Map.Marker.js"
  - "Source/Behaviors/Behavior.Map.Point.js"
  - "Source/Behaviors/Behavior.Map.PolyLine.js"